PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.

FIELD !P_URL1 MODULE %_P_URL1 .

FIELD !P_URL2 MODULE %_P_URL2 .

FIELD !P_ID MODULE %_P_ID .

FIELD !P_PROXY MODULE %_P_PROXY .

FIELD !P_PXPORT MODULE %_P_PXPORT .

FIELD !P_PUSER MODULE %_P_PUSER .

FIELD !P_PPWD MODULE %_P_PPWD .


CHAIN.
  FIELD P_PROXY .
  FIELD P_PXPORT .
  FIELD P_PUSER .
  FIELD P_PPWD .
    MODULE %_BLOCK_1000003.
ENDCHAIN.

CHAIN.
  FIELD P_URL1 .
  FIELD P_URL2 .
  FIELD P_ID .
  FIELD P_PROXY .
  FIELD P_PXPORT .
  FIELD P_PUSER .
  FIELD P_PPWD .
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.